CASMPET 6721
Cray-HPE/istio pull request #23
Opened 2024-06-26 23:27 UTC by arka-pramanik-hpe

Upgrade Istio Images to 1.19.10

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-06-28 14:16 UTC, rajeshranganathan-hpe approved these changes

2024-07-01 05:28 UTC, KJ-HareshKumar approved these changes

2024-07-01 15:31 UTC, dborman-hpe requested changes
There are a lot of merge conflicts that need to be sorted out before this can be merged

2024-07-01 22:15 UTC, arka-pramanik-hpe commented
Since we take changes from upstream and then add our build commits over them so the branch history is fully different than previous and so it can't be merged normally.
I had a chat with @mtupitsyn regarding this and finally we merged the changes by renaming the branch and updating the default branch.

This is how @bo-quan has also done the last time as evident from his upgrade notes which he has shared!

2024-07-01 22:16 UTC, arka-pramanik-hpe commented
Since we take changes from upstream and then add our build commits over them so the branch history is fully different than previous and so it can't be merged normally.
I had a chat with @mtupitsyn regarding this and finally we merged the changes by renaming the branch and updating the default branch.

This is how @bo-quan has also done the last time as evident from his upgrade notes which he has shared!

2024-07-01 22:16 UTC, closed without merging